package informix

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/pkg/errors"

	storepb "github.com/bytebase/bytebase/backend/generated-go/store"
)

// Dump dumps the database schema.
func (d *Driver) Dump(ctx context.Context, out io.Writer, dbSchema *storepb.DatabaseSchemaMetadata) error {
	if dbSchema == nil {
		return errors.New("database schema metadata is required")
	}

	// Write header comment
	if _, err := fmt.Fprintf(out, "-- Informix Database Schema Dump\n"); err != nil {
		return errors.Wrapf(err, "failed to write header")
	}
	if _, err := fmt.Fprintf(out, "-- Database: %s\n", dbSchema.Name); err != nil {
		return errors.Wrapf(err, "failed to write database name")
	}
	if _, err := fmt.Fprintf(out, "-- Generated by Bytebase\n\n"); err != nil {
		return errors.Wrapf(err, "failed to write generator comment")
	}

	// Dump each schema
	for _, schema := range dbSchema.Schemas {
		if err := d.dumpSchema(ctx, out, schema); err != nil {
			return errors.Wrapf(err, "failed to dump schema %s", schema.Name)
		}
	}

	return nil
}

// dumpSchema dumps a single schema
func (d *Driver) dumpSchema(ctx context.Context, out io.Writer, schema *storepb.SchemaMetadata) error {
	// Write schema header
	if _, err := fmt.Fprintf(out, "-- Schema: %s\n", schema.Name); err != nil {
		return errors.Wrapf(err, "failed to write schema header")
	}

	// Dump tables
	for _, table := range schema.Tables {
		if err := d.dumpTable(ctx, out, table); err != nil {
			return errors.Wrapf(err, "failed to dump table %s", table.Name)
		}
	}

	// Dump views
	for _, view := range schema.Views {
		if err := d.dumpView(ctx, out, view); err != nil {
			return errors.Wrapf(err, "failed to dump view %s", view.Name)
		}
	}

	// Dump functions/procedures
	for _, function := range schema.Functions {
		if err := d.dumpFunction(ctx, out, function); err != nil {
			return errors.Wrapf(err, "failed to dump function %s", function.Name)
		}
	}

	return nil
}

// dumpTable dumps a single table definition
func (d *Driver) dumpTable(ctx context.Context, out io.Writer, table *storepb.TableMetadata) error {
	// Write table header
	if _, err := fmt.Fprintf(out, "\n-- Table: %s\n", table.Name); err != nil {
		return errors.Wrapf(err, "failed to write table header")
	}

	// Start CREATE TABLE statement
	if _, err := fmt.Fprintf(out, "CREATE TABLE %s (\n", table.Name); err != nil {
		return errors.Wrapf(err, "failed to write CREATE TABLE")
	}

	// Dump columns
	var columnDefs []string
	for _, column := range table.Columns {
		colDef, err := d.generateColumnDefinition(column)
		if err != nil {
			return errors.Wrapf(err, "failed to generate column definition for %s", column.Name)
		}
		columnDefs = append(columnDefs, colDef)
	}

	// Write column definitions
	if _, err := fmt.Fprintf(out, "    %s\n", strings.Join(columnDefs, ",\n    ")); err != nil {
		return errors.Wrapf(err, "failed to write column definitions")
	}

	// Close CREATE TABLE statement
	if _, err := fmt.Fprintf(out, ");\n"); err != nil {
		return errors.Wrapf(err, "failed to close CREATE TABLE")
	}

	// Dump indexes
	for _, index := range table.Indexes {
		if err := d.dumpIndex(ctx, out, table.Name, index); err != nil {
			return errors.Wrapf(err, "failed to dump index %s", index.Name)
		}
	}

	// Dump foreign keys
	for _, foreignKey := range table.ForeignKeys {
		if err := d.dumpForeignKey(ctx, out, table.Name, foreignKey); err != nil {
			return errors.Wrapf(err, "failed to dump foreign key %s", foreignKey.Name)
		}
	}

	return nil
}

// generateColumnDefinition generates a column definition string
func (d *Driver) generateColumnDefinition(column *storepb.ColumnMetadata) (string, error) {
	var parts []string

	// Column name
	parts = append(parts, column.Name)

	// Column type - this would need to be mapped from Bytebase types to Informix types
	// For now, use a simple mapping
	columnType := d.mapColumnType(column)
	parts = append(parts, columnType)

	// NOT NULL constraint
	if !column.Nullable {
		parts = append(parts, "NOT NULL")
	}

	// Default value (simplified implementation)
	// Note: Default value handling would need to be implemented based on the actual schema
	// if column.HasDefault {
	//     parts = append(parts, fmt.Sprintf("DEFAULT %s", column.Default))
	// }

	// Comment (Informix doesn't have inline comments, but we can note it)
	if column.Comment != "" {
		parts = append(parts, fmt.Sprintf("-- %s", column.Comment))
	}

	return strings.Join(parts, " "), nil
}

// mapColumnType maps Bytebase column types to Informix types
func (d *Driver) mapColumnType(column *storepb.ColumnMetadata) string {
	// This is a basic mapping - a complete implementation would handle
	// all Bytebase column types and their properties
	
	// For now, return a generic type based on the comment field
	// which should contain the original Informix type information
	if strings.Contains(column.Comment, "Informix type:") {
		// Extract type information from comment
		// This is a simplification - real implementation would parse the type properly
		return "VARCHAR(255)" // Default fallback
	}

	// Basic type mapping (would need to be expanded)
	return "VARCHAR(255)"
}

// dumpView dumps a single view definition
func (d *Driver) dumpView(ctx context.Context, out io.Writer, view *storepb.ViewMetadata) error {
	// Write view header
	if _, err := fmt.Fprintf(out, "\n-- View: %s\n", view.Name); err != nil {
		return errors.Wrapf(err, "failed to write view header")
	}

	// Write CREATE VIEW statement
	if view.Definition != "" {
		if _, err := fmt.Fprintf(out, "CREATE VIEW %s AS\n%s;\n", view.Name, view.Definition); err != nil {
			return errors.Wrapf(err, "failed to write CREATE VIEW")
		}
	} else {
		if _, err := fmt.Fprintf(out, "-- View definition not available for %s\n", view.Name); err != nil {
			return errors.Wrapf(err, "failed to write view placeholder")
		}
	}

	return nil
}

// dumpFunction dumps a single function/procedure definition
func (d *Driver) dumpFunction(ctx context.Context, out io.Writer, function *storepb.FunctionMetadata) error {
	// Write function header
	if _, err := fmt.Fprintf(out, "\n-- Function/Procedure: %s\n", function.Name); err != nil {
		return errors.Wrapf(err, "failed to write function header")
	}

	// Write function definition
	if function.Definition != "" {
		if _, err := fmt.Fprintf(out, "%s;\n", function.Definition); err != nil {
			return errors.Wrapf(err, "failed to write function definition")
		}
	} else {
		if _, err := fmt.Fprintf(out, "-- Function definition not available for %s\n", function.Name); err != nil {
			return errors.Wrapf(err, "failed to write function placeholder")
		}
	}

	return nil
}

// dumpIndex dumps a single index definition
func (d *Driver) dumpIndex(ctx context.Context, out io.Writer, tableName string, index *storepb.IndexMetadata) error {
	if index.Primary {
		// Primary key constraint
		if _, err := fmt.Fprintf(out, "ALTER TABLE %s ADD CONSTRAINT %s PRIMARY KEY (%s);\n",
			tableName, index.Name, strings.Join(index.Expressions, ", ")); err != nil {
			return errors.Wrapf(err, "failed to write primary key constraint")
		}
	} else if index.Unique {
		// Unique index
		if _, err := fmt.Fprintf(out, "CREATE UNIQUE INDEX %s ON %s (%s);\n",
			index.Name, tableName, strings.Join(index.Expressions, ", ")); err != nil {
			return errors.Wrapf(err, "failed to write unique index")
		}
	} else {
		// Regular index
		if _, err := fmt.Fprintf(out, "CREATE INDEX %s ON %s (%s);\n",
			index.Name, tableName, strings.Join(index.Expressions, ", ")); err != nil {
			return errors.Wrapf(err, "failed to write index")
		}
	}

	return nil
}

// dumpForeignKey dumps a single foreign key constraint
func (d *Driver) dumpForeignKey(ctx context.Context, out io.Writer, tableName string, foreignKey *storepb.ForeignKeyMetadata) error {
	if _, err := fmt.Fprintf(out, "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s);\n",
		tableName, foreignKey.Name,
		strings.Join(foreignKey.Columns, ", "),
		foreignKey.ReferencedTable,
		strings.Join(foreignKey.ReferencedColumns, ", ")); err != nil {
		return errors.Wrapf(err, "failed to write foreign key constraint")
	}

	return nil
}